#version 450

layout(local_size_x = 256) in;


layout(std430, binding = 7) buffer GroupOffset
{
    uint groupOffsets[];
};
layout(std430, binding = 8) buffer Offsets
{
    uint offsets[];
};
layout(std430, binding = 9) buffer PartialSums
{ 
    uint partialSums[]; 
};
layout(std430,binding=10) buffer Counter
{
    uint visibleCount;
};

void main() {
    uint digit = gl_LocalInvocationID.x;
    uint blockID = gl_WorkGroupID.x;
    uint numGroups = (visibleCount + 255) / 256;

    uint blockBase = partialSums[blockID * 256 + digit];

    for (uint i = 0; i < 16; i++) {
        uint g = blockID * 16 + i;
        if (g < numGroups) {
            groupOffsets[g * 256 + digit] += blockBase;
        }
    }
}